# Sử dụng Node.js bản nhẹ (Alpine)
FROM node:18-alpine

# Tạo thư mục làm việc trong container
WORKDIR /app

# Copy file package để cài thư viện trước (tối ưu cache)
COPY package*.json ./
RUN npm install

# Copy toàn bộ code còn lại
COPY . .

# Mở port 5000
EXPOSE 5000

# Lệnh chạy ứng dụng
CMD ["npm", "start"]